name: Price Update Checker

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-prices:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pandas khayyam requests
        
    # Skip Chrome install step, because it's already there!
    
    - name: Run price checker
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_IDS: ${{ secrets.CHAT_IDS }}
      run: python price_checker.py
      
    - name: Commit and push if data changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add market_price_updates.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "Update price data [skip ci]"
        git push
